### ISSUE TITLE
Can't disable widget action via "action_set_enabled"

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#23]
Apparently the `action_set_enabled` method doesn't do anything for some reason. This can be tested by putting `widget.action_set_enabled("my-widget.set-label", false);` [in this line of this test](https://github.com/jf2048/gobject/blob/de4e5e90f0ea817e83cd7d2bd212d44302286d45/tests/gtk4_widget.rs#L114). The test will not fail, so the action is still enabled.

Version: de4e5e90f0ea817e83cd7d2bd212d44302286d45.

**Comment by jf2048** [comment]
That function only works with actions installed with `install_action`, which I didn't use at all, it doesn't support stateful actions. The group has to be bound and then you can get the action and call `set_enabled` on it. I thought of using `install_action` with non-stateful actions but it seemed confusing, since if you add a state then `action_set_enabled` will stop working again.

I guess something more idiomatic might be to use `install_action` for widget actions and just don't support stateful actions or getting the action group, because you're supposed to use property actions for that?

**Comment by jf2048** [comment]
It's possible this is also a GTK bug, since `activate_action` is able to find actions from groups, but `action_set_enabled` isn't?

**Comment by melix99** [comment]
>I guess something more idiomatic might be to use install_action for widget actions

Honestly I expected that the `widget_action` macro was just an integrated way of using `install_action`. So, while trying to port a widget to gobject macros, I didn't understand what was wrong with `action_set_enabled` not working anymore.

> and just don't support stateful actions or getting the action group, because you're supposed to use property actions for that?

Yeah, I'm pretty sure you're supposed to use that for state values.

**Comment by jf2048** [comment]
For now I'll probably change it back to `install_action` then
